// File: src/templates/registry.ts
import type { TemplateDefinitionV2 } from '../types/resume';

// ─── ATS-Friendly Templates ──────────────────────────────────────────────────

const atsModern: TemplateDefinitionV2 = {
  version: 2,
  id: 'ats-modern',
  name: 'ATS Modern',
  category: 'ats',
  description: 'Clean single-column layout optimized for ATS parsing. Blue accents, easy-to-read bullets.',
  isAtsFriendly: true,
  tags: ['ats', 'single-column', 'clean', 'blue'],
  flags: { supportsPhoto: false, supportsIcons: true, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'underline',
  tokens: {
    primaryColor: '#1d4ed8',
    accentColor: '#3b82f6',
    bgColor: '#ffffff',
    sidebarBg: '#f0f4ff',
    sidebarText: '#1d4ed8',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'ats-modern', fontFamily: 'Inter', fontSize: 13, primaryColor: '#1d4ed8', accentColor: '#3b82f6', spacing: 'normal', columns: 1 },
};

const atsClassic: TemplateDefinitionV2 = {
  version: 2,
  id: 'ats-classic',
  name: 'ATS Classic',
  category: 'ats',
  description: 'Traditional centered header, serif body. Ideal for academic and formal applications.',
  isAtsFriendly: true,
  tags: ['ats', 'serif', 'formal', 'academic', 'centered'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'centered',
  sectionStyle: 'underline',
  tokens: {
    primaryColor: '#1e3a5f',
    accentColor: '#4a7ab5',
    bgColor: '#ffffff',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e3a5f',
    textColor: '#1a1a2e',
    mutedColor: '#64748b',
    fontFamily: 'Georgia, serif',
    headingFont: 'Georgia, serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'ats-classic', fontFamily: 'Georgia', fontSize: 13, primaryColor: '#1e3a5f', accentColor: '#4a7ab5', spacing: 'normal', columns: 1 },
};

const atsMinimal: TemplateDefinitionV2 = {
  version: 2,
  id: 'ats-minimal',
  name: 'ATS Minimal',
  category: 'ats',
  description: 'Ultra-clean grayscale layout with generous whitespace. Maximum ATS compatibility.',
  isAtsFriendly: true,
  tags: ['ats', 'grayscale', 'minimal', 'whitespace'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'compact',
  sectionStyle: 'minimal',
  tokens: {
    primaryColor: '#111827',
    accentColor: '#6b7280',
    bgColor: '#ffffff',
    sidebarBg: '#f9fafb',
    sidebarText: '#374151',
    textColor: '#1f2937',
    mutedColor: '#9ca3af',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'ats-minimal', fontFamily: 'Inter', fontSize: 13, primaryColor: '#111827', accentColor: '#6b7280', spacing: 'relaxed', columns: 1 },
};

const atsTech: TemplateDefinitionV2 = {
  version: 2,
  id: 'ats-tech',
  name: 'ATS Tech',
  category: 'ats',
  description: 'Developer-optimized layout with green accents and filled section bars. ATS-safe.',
  isAtsFriendly: true,
  tags: ['ats', 'tech', 'developer', 'green'],
  flags: { supportsPhoto: false, supportsIcons: true, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'filled-bar',
  tokens: {
    primaryColor: '#047857',
    accentColor: '#10b981',
    bgColor: '#ffffff',
    sidebarBg: '#ecfdf5',
    sidebarText: '#047857',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Roboto, sans-serif',
    headingFont: 'Roboto, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'ats-tech', fontFamily: 'Roboto', fontSize: 13, primaryColor: '#047857', accentColor: '#10b981', spacing: 'compact', columns: 1 },
};

const atsExecutive: TemplateDefinitionV2 = {
  version: 2,
  id: 'ats-executive',
  name: 'ATS Executive',
  category: 'ats',
  description: 'Bold, authoritative layout for C-level and senior leadership roles.',
  isAtsFriendly: true,
  tags: ['ats', 'executive', 'leadership', 'bold', 'navy'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'centered',
  sectionStyle: 'filled-bar',
  tokens: {
    primaryColor: '#0f172a',
    accentColor: '#334155',
    bgColor: '#ffffff',
    sidebarBg: '#f1f5f9',
    sidebarText: '#0f172a',
    textColor: '#0f172a',
    mutedColor: '#475569',
    fontFamily: 'Raleway, sans-serif',
    headingFont: 'Raleway, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'ats-executive', fontFamily: 'Raleway', fontSize: 13, primaryColor: '#0f172a', accentColor: '#334155', spacing: 'normal', columns: 1 },
};

// ─── Creative / Visual Templates ─────────────────────────────────────────────

const elegantSidebar: TemplateDefinitionV2 = {
  version: 2,
  id: 'elegant-sidebar',
  name: 'Elegant Sidebar',
  category: 'elegant',
  description: 'Sophisticated left-sidebar layout with photo support. Purple accents, two-tone design.',
  isAtsFriendly: false,
  tags: ['creative', 'sidebar', 'photo', 'purple', 'elegant'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: true, supportsColumns: true },
  layout: 'sidebar-left',
  headerVariant: 'left',
  sectionStyle: 'dot-rule',
  sidebarSections: ['skills', 'languages', 'certifications', 'awards', 'achievements'],
  tokens: {
    primaryColor: '#7c3aed',
    accentColor: '#a78bfa',
    bgColor: '#ffffff',
    sidebarBg: '#1e1b4b',
    sidebarText: '#e0e7ff',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: 'Raleway, sans-serif',
    headingFont: 'Raleway, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'elegant-sidebar', fontFamily: 'Raleway', fontSize: 13, primaryColor: '#7c3aed', accentColor: '#a78bfa', spacing: 'normal', columns: 2 },
};

const timelinePro: TemplateDefinitionV2 = {
  version: 2,
  id: 'timeline-pro',
  name: 'Timeline Pro',
  category: 'creative',
  description: 'Vertical timeline for experience. Striking banner header. Perfect for storytelling.',
  isAtsFriendly: false,
  tags: ['timeline', 'creative', 'blue', 'banner', 'visual'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'banner',
  headerVariant: 'banner',
  sectionStyle: 'dot-rule',
  tokens: {
    primaryColor: '#1e40af',
    accentColor: '#60a5fa',
    bgColor: '#ffffff',
    sidebarBg: '#eff6ff',
    sidebarText: '#1e40af',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'timeline-pro', fontFamily: 'Inter', fontSize: 13, primaryColor: '#1e40af', accentColor: '#60a5fa', spacing: 'normal', columns: 1 },
};

const cardModern: TemplateDefinitionV2 = {
  version: 2,
  id: 'card-modern',
  name: 'Card Modern',
  category: 'modern',
  description: 'Projects as visual cards with icon-led sections. Indigo/violet palette.',
  isAtsFriendly: false,
  tags: ['cards', 'modern', 'icons', 'indigo', 'visual'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: true, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'icon-led',
  tokens: {
    primaryColor: '#4f46e5',
    accentColor: '#818cf8',
    bgColor: '#ffffff',
    sidebarBg: '#eef2ff',
    sidebarText: '#4f46e5',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'card-modern', fontFamily: 'Inter', fontSize: 13, primaryColor: '#4f46e5', accentColor: '#818cf8', spacing: 'normal', columns: 1 },
};

const twoColAccent: TemplateDefinitionV2 = {
  version: 2,
  id: 'two-col-accent',
  name: 'Two Column Accent',
  category: 'modern',
  description: 'Skills and key info in a right sidebar with icon-led sections. Teal palette.',
  isAtsFriendly: false,
  tags: ['two-column', 'sidebar', 'teal', 'icons'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: false, supportsColumns: true },
  layout: 'sidebar-right',
  headerVariant: 'banner',
  sectionStyle: 'icon-led',
  sidebarSections: ['skills', 'languages', 'certifications', 'awards', 'education'],
  tokens: {
    primaryColor: '#0d9488',
    accentColor: '#2dd4bf',
    bgColor: '#ffffff',
    sidebarBg: '#f0fdfa',
    sidebarText: '#0d9488',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'two-col-accent', fontFamily: 'Inter', fontSize: 13, primaryColor: '#0d9488', accentColor: '#2dd4bf', spacing: 'normal', columns: 2 },
};

const darkHeader: TemplateDefinitionV2 = {
  version: 2,
  id: 'dark-header',
  name: 'Dark Header',
  category: 'modern',
  description: 'High-contrast dark banner header with a clean light body. Bold and professional.',
  isAtsFriendly: false,
  tags: ['dark', 'banner', 'contrast', 'bold'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'banner',
  headerVariant: 'banner',
  sectionStyle: 'underline',
  tokens: {
    primaryColor: '#0f172a',
    accentColor: '#f59e0b',
    bgColor: '#ffffff',
    sidebarBg: '#f8fafc',
    sidebarText: '#0f172a',
    textColor: '#111827',
    mutedColor: '#64748b',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'dark-header', fontFamily: 'Inter', fontSize: 13, primaryColor: '#0f172a', accentColor: '#f59e0b', spacing: 'normal', columns: 1 },
};

const gradientAccent: TemplateDefinitionV2 = {
  version: 2,
  id: 'gradient-accent',
  name: 'Gradient Accent',
  category: 'creative',
  description: 'Stylish gradient sidebar accent line with dot-rule sections. Print-safe.',
  isAtsFriendly: false,
  tags: ['gradient', 'purple', 'pink', 'stylish', 'creative'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: true, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'dot-rule',
  tokens: {
    primaryColor: '#7c3aed',
    accentColor: '#ec4899',
    bgColor: '#ffffff',
    sidebarBg: '#fdf4ff',
    sidebarText: '#7c3aed',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Raleway, sans-serif',
    headingFont: 'Raleway, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'gradient-accent', fontFamily: 'Raleway', fontSize: 13, primaryColor: '#7c3aed', accentColor: '#ec4899', spacing: 'normal', columns: 1 },
};

const infographicLite: TemplateDefinitionV2 = {
  version: 2,
  id: 'infographic-lite',
  name: 'Infographic Lite',
  category: 'creative',
  description: 'Visual sidebar with skill bars and icons. ATS-safe fallback disables skill bars.',
  isAtsFriendly: false,
  tags: ['infographic', 'visual', 'skill-bars', 'orange', 'sidebar'],
  flags: { supportsPhoto: true, supportsIcons: true, supportsBackgroundPattern: true, supportsColumns: true },
  layout: 'sidebar-left',
  headerVariant: 'banner',
  sectionStyle: 'icon-led',
  sidebarSections: ['skills', 'languages', 'certifications', 'achievements'],
  tokens: {
    primaryColor: '#c2410c',
    accentColor: '#fb923c',
    bgColor: '#ffffff',
    sidebarBg: '#431407',
    sidebarText: '#fed7aa',
    textColor: '#111827',
    mutedColor: '#6b7280',
    fontFamily: 'Lato, sans-serif',
    headingFont: 'Lato, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'infographic-lite', fontFamily: 'Lato', fontSize: 13, primaryColor: '#c2410c', accentColor: '#fb923c', spacing: 'normal', columns: 2 },
};

// ─── Plain White Templates (no color, ATS-friendly) ──────────────────────────

const plainClassic: TemplateDefinitionV2 = {
  version: 2,
  id: 'plain-classic',
  name: 'Plain Classic',
  category: 'ats',
  description: 'Pure white, serif, centered header. Traditional academic/formal style. Zero color — maximum ATS compatibility.',
  isAtsFriendly: true,
  tags: ['plain', 'white', 'ats', 'serif', 'centered', 'classic', 'academic'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'centered',
  sectionStyle: 'underline',
  tokens: {
    primaryColor: '#111111',
    accentColor: '#444444',
    bgColor: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#111111',
    textColor: '#111111',
    mutedColor: '#555555',
    fontFamily: 'Georgia, serif',
    headingFont: 'Georgia, serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'plain-classic', fontFamily: 'Georgia', fontSize: 13, primaryColor: '#111111', accentColor: '#444444', spacing: 'normal', columns: 1 },
};

const plainModern: TemplateDefinitionV2 = {
  version: 2,
  id: 'plain-modern',
  name: 'Plain Modern',
  category: 'ats',
  description: 'Pure white, left-aligned header, generous whitespace, minimal section headings. Clean and contemporary.',
  isAtsFriendly: true,
  tags: ['plain', 'white', 'ats', 'modern', 'minimal', 'left', 'sans-serif'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'minimal',
  tokens: {
    primaryColor: '#111111',
    accentColor: '#333333',
    bgColor: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#111111',
    textColor: '#111111',
    mutedColor: '#555555',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'plain-modern', fontFamily: 'Inter', fontSize: 13, primaryColor: '#111111', accentColor: '#333333', spacing: 'relaxed', columns: 1 },
};

const plainCompact: TemplateDefinitionV2 = {
  version: 2,
  id: 'plain-compact',
  name: 'Plain Compact',
  category: 'ats',
  description: 'Pure white, compact header, dense layout optimized for one-page resumes. Maximum content density.',
  isAtsFriendly: true,
  tags: ['plain', 'white', 'ats', 'compact', 'dense', 'one-page'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'compact',
  sectionStyle: 'filled-bar',
  tokens: {
    primaryColor: '#111111',
    accentColor: '#333333',
    bgColor: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#111111',
    textColor: '#111111',
    mutedColor: '#555555',
    fontFamily: 'Arial, Helvetica, sans-serif',
    headingFont: 'Arial, Helvetica, sans-serif',
    fontSize: 12,
  },
  defaultStyles: { templateId: 'plain-compact', fontFamily: 'Arial', fontSize: 12, primaryColor: '#111111', accentColor: '#333333', spacing: 'compact', columns: 1 },
};

const plainTwoColumn: TemplateDefinitionV2 = {
  version: 2,
  id: 'plain-two-column',
  name: 'Plain Two Column',
  category: 'ats',
  description: 'Pure white two-column layout. Skills/certs in right sidebar, experience/education in main column.',
  isAtsFriendly: true,
  tags: ['plain', 'white', 'ats', 'two-column', 'sidebar'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: true },
  layout: 'sidebar-right',
  headerVariant: 'left',
  sectionStyle: 'underline',
  sidebarSections: ['skills', 'languages', 'certifications', 'awards', 'courses'],
  tokens: {
    primaryColor: '#111111',
    accentColor: '#333333',
    bgColor: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#111111',
    textColor: '#111111',
    mutedColor: '#555555',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Inter, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'plain-two-column', fontFamily: 'Inter', fontSize: 13, primaryColor: '#111111', accentColor: '#333333', spacing: 'normal', columns: 2 },
};

const plainSkillsFirst: TemplateDefinitionV2 = {
  version: 2,
  id: 'plain-skills-first',
  name: 'Plain Skills First',
  category: 'ats',
  description: 'Pure white single-column with dot-rule section dividers. Designed for skills-forward resumes.',
  isAtsFriendly: true,
  tags: ['plain', 'white', 'ats', 'skills', 'dot-rule', 'single-column'],
  flags: { supportsPhoto: false, supportsIcons: false, supportsBackgroundPattern: false, supportsColumns: false },
  layout: 'single',
  headerVariant: 'left',
  sectionStyle: 'dot-rule',
  tokens: {
    primaryColor: '#111111',
    accentColor: '#444444',
    bgColor: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#111111',
    textColor: '#111111',
    mutedColor: '#555555',
    fontFamily: 'Roboto, sans-serif',
    headingFont: 'Roboto, sans-serif',
    fontSize: 13,
  },
  defaultStyles: { templateId: 'plain-skills-first', fontFamily: 'Roboto', fontSize: 13, primaryColor: '#111111', accentColor: '#444444', spacing: 'normal', columns: 1 },
};

// ─── Registry ─────────────────────────────────────────────────────────────────

export const TEMPLATE_REGISTRY_V2: TemplateDefinitionV2[] = [
  atsModern,
  atsClassic,
  atsMinimal,
  atsTech,
  atsExecutive,
  elegantSidebar,
  timelinePro,
  cardModern,
  twoColAccent,
  darkHeader,
  gradientAccent,
  infographicLite,
  plainClassic,
  plainModern,
  plainCompact,
  plainTwoColumn,
  plainSkillsFirst,
];

export const TEMPLATE_MAP_V2 = Object.fromEntries(TEMPLATE_REGISTRY_V2.map((t) => [t.id, t]));

/** Check if a template ID belongs to V2 registry */
export function isV2Template(id: string): boolean {
  return id in TEMPLATE_MAP_V2;
}
